version: '3.1'

services:
  jenkins:
    build: .
    restart: always
    ports:
      - 8001:8001
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  jenkins-data:

      