services:
  jenkins:
    build: .
    container_name: jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    environment:
      - host_ip=191.252.210.226
      - username=jenkins